#
# deploy.yml
#
# Simple deployment of Synse Server & Synse AMT Plugin
#
version: "3"
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
      - 5000:5000
    links:
      - amt-plugin

  amt-plugin:
    container_name: amt-plugin
    image: vaporio/amt-plugin
    ports:
      - 5001:5001
    volumes:
      - ./deploy/devices:/tmp/devices
    environment:
      PLUGIN_DEVICE_PATH: /tmp/devices
